export ANDROID_SDK=$HOME/Library/Android/sdk

#source ./git-completion.bash
#source ./gradle-tab-completion.bash
#if [ -f /sw/etc/bash_completion ]; then
#   . /sw/etc/bash_completion
#fi
source ./function/pushapk.sh

# load custom executable functions
for function in ~/.zsh/functions/*; do
  source $function
done
