alias zshconfig="atom ~/.zshrc"
alias hyperconfig="atom ~/.hyper.js"
alias ohmyzsh="atom ~/.oh-my-zsh"
#alias notes="atom ~/Dropbox/Apps/Notational\ Data"
#alias notesFile="~/Dropbox/Apps/Notational\ Data"
alias ll="exa -lghuU --git"
alias emptytrash="sudo rm -rfv /Volumes/*/.Trashes; sudo rm -rfv ~/.Trash; sudo rm -rfv /private/var/log/asl/*.asl"
alias extip="dig +short myip.opendns.com @resolver1.opendns.com"
alias sniff="sudo ngrep -d 'en0' -t '^(GET|POST) ' 'tcp and port 80'"
alias httpdump="sudo tcpdump -i en1 -n -s 0 -w - | grep -a -o -E \"Host\: .*|GET \/.*\""
alias timer='echo "Timer started. Stop with Ctrl-D." && date && time cat && date'
alias filetree="ls -R | grep ":$" | sed -e 's/:$//' -e 's/[^-][^\/]*\//--/g' -e 's/^/ /' -e 's/-/|/'"
alias reload="zsh --login"
alias reload!='. ~/.zshrc'
alias rollmac="sudo openssl rand -hex 6 | sed 's/\(..\)/\1:/g; s/.$//' | xargs"
alias cls='clear' # obvsly
alias dnuke='docker stop $(docker ps -a -q) && docker rm $(docker ps -a -q) && docker rmi $(docker images -q)'
alias rpi_ip="arp -a | grep b8:27:eb | grep -Eo '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}'"
alias purgedns="sudo killall -HUP mDNSResponder && sudo killall mDNSResponderHelper && sudo dscacheutil -flushcache"
alias fixlines="find ./ -type f -exec perl -pi -e 's/\r\n|\n|\r/\n/g' {} \;"
export PATH="/usr/local/sbin:$PATH"
