# your projects folder so that we can `c [tab]` to
export PROJECTS="~/Code"

# shortcut to this dotfiles path is $DOTFILES
export DOTFILES="~/.dotfiles"

# Your personal Dropbox folder
#export DROPBOX="$HOME/Dropbox (Personal)"

# source the base zshrc configurations first
for config_file (~/.dotfiles/dot-zsh/config/*.zsh) source $config_file

# source the remaining zsh config files
# the `^zsh` bit means all directories _except_ the `zsh` directory
for config_file (~/.dotfiles/^dot-zsh/config/*.zsh) source $config_file

 # show full path in command prompt
 export PS1="%~ %% "
# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/russ/Code/cloud/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/russ/Code/cloud/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/russ/Code/cloud/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/russ/Code/cloud/google-cloud-sdk/completion.zsh.inc'; fi

# Added by Amplify CLI binary installer
export PATH="$HOME/.amplify/bin:$PATH"

source ~/.dotfiles/dot-zsh/tools/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
export PATH=$PATH:/Users/RMacDonald/.privado/bin
